services:
  postgres:
    container_name: myPostgreSQL
    image: postgres:latest
    env_file:
      - .env
    volumes:
      - type: bind
        source: /opt/postgreSQL
        target: /var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - myDatabaseNetwork

networks:
  myDatabaseNetwork:
    name: myDatabaseNetwork