services:
  postgres:
    container_name: myPostgreSQL
    image: postgres:latest
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - myDatabaseNetwork

networks:
  myDatabaseNetwork:
    name: myDatabaseNetwork

volumes:
  postgres_data:
